openapi: 3.0.0
info:
  title: Fitchoice API
  version: "1.0.0"
servers:
  # Added by API Auto Mocking Plugin
  - url: http://158.160.145.40:8080/api/v1
tags:
  - name: auth
    description: Методы аутентификации и регистрации пользователей
paths:
  /auth/sendCode:
    post:
      tags:
        - auth
      summary: Отправка кода подтверждения на email
      operationId: sendCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendCodeInput"
      responses:
        "200":
          description: Код успешно отправлен
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Verification code sent"
        "400":
          description: Неверный email или ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/registration:
    post:
      tags:
        - auth
      summary: Регистрация нового пользователя
      operationId: registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationInput"
      responses:
        "200":
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Ошибка валидации или неверный код подтверждения
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка на стороне сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/refresh:
    post:
      tags:
        - auth
      summary: Обновление токенов доступа
      operationId: refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshInput"
      responses:
        "200":
          description: Токены успешно обновлены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Неверный запрос (отсутствует refresh_token)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Неверный или просроченный refresh-токен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/login:
    post:
      tags:
        - auth
      summary: Авторизация пользователя
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Успешный вход, возвращаются токены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Неверный email или пароль
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
                
 
          get:
            tags:
              - user
            summary: Получение текущей тренировочной программы пользователя
            operationId: getTrainingProgram
            parameters:
              - name: userId
                in: path
                required: true
                schema:
                  type: string
            responses:
              "200":
                description: Тренировочная программа пользователя
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        $ref: "#/components/schemas/TrainingResponse"
              "500":
                description: Ошибка сервера
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/ErrorResponse"
  
  /user/update/{id}:
    post:
      tags:
        - user
      summary: Обновление данных пользователя
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          description: ID пользователя
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Иван"
                promocode:
                  type: string
                  example: "FIT2025"
                gender:
                  type: string
                  example: "male"
                age:
                  type: integer
                  example: 25
                height:
                  type: number
                  format: float
                  example: 180
                weight:
                  type: number
                  format: float
                  example: 75.5
                train_days:
                  type: integer
                  example: 21
                train_goals:
                  type: integer
                  example: 0
                train_frequency:
                  type: integer
                  example: 4
                main_direction:
                  type: integer
                  example: 0
                secondary_direction:
                  type: integer
                  example: 0
      responses:
        "200":
          description: Данные пользователя успешно обновлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "updated"
        "400":
          description: Ошибка запроса (пустой или неверный JSON)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка на стороне сервера при обновлении данных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"


  /trainings/plan/{id}:
    post:
      tags:
        - trainings
      summary: Построение тренировочного плана для пользователя
      operationId: buildTrainingPlan
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: План успешно построен
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Training plan built successfully"
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/plan/{userId}:
    get:
      tags:
        - trainings
      summary: Получение плана тренировок пользователя
      operationId: getTrainingProgram
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Список тренировочных дней с упражнениями
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    periodId:
                      type: integer
                    date:
                      type: string
                      format: date
                    dayActivities:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          type:
                            type: string
                          duration:
                            type: integer
                          experience:
                            type: string
                          progress:
                            type: array
                            items:
                              type: integer
        "404":
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/train/{trainingId}:
    get:
      tags:
        - trainings
      summary: Получение информации по тренировке
      operationId: getTrainInformation
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация о тренировке
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  difficulty:
                    type: string
                  experience:
                    type: string
                  inventory:
                    type: array
                    items:
                      type: string
                  exercises:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        duration:
                          type: integer
                        progress:
                          type: integer
                        sets:
                          type: integer
                        reps:
                          type: integer
                        isAi:
                          type: boolean
                        videoUrl:
                          type: string
        "404":
          description: Тренировка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "400":
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/report:
    post:
      tags:
        - trainings
      summary: Создание или обновление отчёта по тренировке
      operationId: createReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                training_id: 1
                report_duration: 45
                report_active_time: 40
                report_cals: 300
                report_technique_quality: 8
      responses:
        "200":
          description: Отчёт обновлён
          content:
            application/json:
              schema:
                type: object
                example:
                  status: report updated
        "400":
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/report/{trainingId}:
    get:
      tags:
        - trainings
      summary: Получение отчёта по тренировке
      operationId: getReport
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация об отчёте
          content:
            application/json:
              schema:
                type: object
                properties:
                  report_duration:
                    type: integer
                  report_active_time:
                    type: integer
                  report_cals:
                    type: integer
                  report_technique_quality:
                    type: integer
        "404":
          description: Отчёт не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/diary:
    post:
      tags:
        - trainings
      summary: Создание или обновление дневника пользователя
      operationId: createDiary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 1
                diary_mood: 5
                diary_wellbeing: 8
                diary_energy_level: 7
                diary_sleep_quality: 9
                diary_sleep_time: "22:30"
                diary_wake_time: "06:30"
                diary_note: "Хорошее самочувствие"
      responses:
        "200":
          description: Дневник обновлён
          content:
            application/json:
              schema:
                type: object
                example:
                  status: diary updated
        "400":
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/diary/{dayId}:
    get:
      tags:
        - trainings
      summary: Получение дневника пользователя по дню
      operationId: getDiary
      parameters:
        - name: dayId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация о дневнике
          content:
            application/json:
              schema:
                type: object
                properties:
                  diary_mood:
                    type: integer
                  diary_wellbeing:
                    type: integer
                  diary_energy_level:
                    type: integer
                  diary_sleep_quality:
                    type: integer
                  diary_sleep_time:
                    type: string
                  diary_wake_time:
                    type: string
                  diary_note:
                    type: string
        "404":
          description: Дневник не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /trainings/exercise:
    post:
      tags:
        - trainings
      summary: Обновление прогресса упражнения
      operationId: executeTraining
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                training_id: 1
                index: 0
                reps: 10
      responses:
        "200":
          description: Прогресс обновлён
          content:
            application/json:
              schema:
                type: object
                example:
                  status: progress updated
        "400":
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Тренировка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    SendCodeInput:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: user@example.com

    RegistrationInput:
      type: object
      required:
        - code
        - email
        - password
      properties:
        code:
          type: integer
          example: 123456
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: StrongPassword123!

    RefreshInput:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: StrongPassword123!

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...


    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: invalid email
        
    TrainingResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 10
        period_id:
          type: integer
          example: 3
        date:
          type: string
          format: date-time
          example: "2025-10-20T12:00:00Z"
        dayActivities:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 1
              type:
                type: string
                example: "strength"
              duration:
                type: integer
                example: 45
              experience:
                type: string
                example: "3 months"
              progress:
                type: array
                items:
                  type: integer
                  example: 5


